server:
  port: 9015

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/dev
    username: root
    password: dbpass
    initialize: true
  jpa:
    database: MYSQL
    show-sql: true  #this shows logs of all sql queries.. turn off once development is finished
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop  #to change to none after first mysql start. Also think about using flyway
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect