version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dbpass
      - MYSQL_DATABASE=dev
  hystrix:
    image: threedeeapp/hystrix-dashboard
    ports:
      - "7979:7979"
# links:
#   - gateway
#   - discovery
  discovery:
    image: threedeeapp/discovery-microservice
    ports:
      - "8761:8761"
  configserver:
    image: threedeeapp/config-microservice
    ports:
      - "8888:8888"
    depends_on:
      - discovery
#  links:
#   - discovery
  gateway:
    image: threedeeapp/api-gateway-microservice
    ports:
      - "10000:10000"
    links:
      - discovery
      - configserver
      - threedeemodel
  threedeemodel:
    image: threedeeapp/threedeemodel-microservice
    depends_on:
      - discovery
      - configserver
      - mysql
#  ports:
#   - "6005:6005"
#user:
#  image: threedeeapp/users-microservice
#  links:
#  - discovery
#   - configserver
#movie:
#  image: threedeeapp/movie-microservice
#  links:
#   - discovery
 #  - configserver
#recommendation:
#  image: threedeeapp/recommendation-microservice
#  links:
#   - discovery
#   - configserver
#moviesui:
#  image: threedeeapp/movies-ui
#  ports:
#     - "9006:9006"
#  links:
#   - discovery
#   - configserver

